# Generated by Django 5.0.3 on 2024-07-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdharImages',
            new_name='AdharImagesOfApplicant',
        ),
        migrations.RenameModel(
            old_name='PanImages',
            new_name='PanImagesOfApplicant',
        ),
        migrations.AlterModelOptions(
            name='adharimagesofapplicant',
            options={'verbose_name': 'Aadhar Image', 'verbose_name_plural': 'Aadhar Images'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='applicantimage',
            options={'verbose_name': 'Applicant Image', 'verbose_name_plural': 'Applicant Images'},
        ),
        migrations.AlterModelOptions(
            name='applicantimagebusiness',
            options={'verbose_name': 'Applicant Business Image', 'verbose_name_plural': 'Applicant Business Images'},
        ),
        migrations.AlterModelOptions(
            name='backgroundverification',
            options={'verbose_name': 'Background Verification', 'verbose_name_plural': 'Background Verifications'},
        ),
        migrations.AlterModelOptions(
            name='balancesheetandplaccount',
            options={'verbose_name': 'Balance Sheet and P&L Account', 'verbose_name_plural': 'Balance Sheets and P&L Accounts'},
        ),
        migrations.AlterModelOptions(
            name='buyers',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterModelOptions(
            name='coapplicant',
            options={'verbose_name': 'Co-Applicant', 'verbose_name_plural': 'Co-Applicants'},
        ),
        migrations.AlterModelOptions(
            name='coapplicantimage',
            options={'verbose_name': 'Co-Applicant Image', 'verbose_name_plural': 'Co-Applicant Images'},
        ),
        migrations.AlterModelOptions(
            name='coapplicantimagebusiness',
            options={'verbose_name': 'Co-Applicant Business Image', 'verbose_name_plural': 'Co-Applicant Business Images'},
        ),
        migrations.AlterModelOptions(
            name='detailsofassociate',
            options={'verbose_name': 'Detail of Associate', 'verbose_name_plural': 'Details of Associates'},
        ),
        migrations.AlterModelOptions(
            name='finalconclusion',
            options={'verbose_name': 'Final Conclusion', 'verbose_name_plural': 'Final Conclusions'},
        ),
        migrations.AlterModelOptions(
            name='guarantor',
            options={'verbose_name': 'Guarantor', 'verbose_name_plural': 'Guarantors'},
        ),
        migrations.AlterModelOptions(
            name='guarantorimage',
            options={'verbose_name': 'Guarantor Image', 'verbose_name_plural': 'Guarantor Images'},
        ),
        migrations.AlterModelOptions(
            name='guarantorimagebusiness',
            options={'verbose_name': 'Guarantor Business Image', 'verbose_name_plural': 'Guarantor Business Images'},
        ),
        migrations.AlterModelOptions(
            name='insurancedetails',
            options={'verbose_name': 'Insurance Detail', 'verbose_name_plural': 'Insurance Details'},
        ),
        migrations.AlterModelOptions(
            name='itrverification',
            options={'verbose_name': 'ITR Verification', 'verbose_name_plural': 'ITR Verifications'},
        ),
        migrations.AlterModelOptions(
            name='manufacturingentities',
            options={'verbose_name': 'Manufacturing Entity', 'verbose_name_plural': 'Manufacturing Entities'},
        ),
        migrations.AlterModelOptions(
            name='otherparticulars',
            options={'verbose_name': 'Other Particular', 'verbose_name_plural': 'Other Particulars'},
        ),
        migrations.AlterModelOptions(
            name='panimagesofapplicant',
            options={'verbose_name': 'PAN Image', 'verbose_name_plural': 'PAN Images'},
        ),
        migrations.AlterModelOptions(
            name='personalassetsofproprietor',
            options={'verbose_name': 'Personal Asset of Proprietor', 'verbose_name_plural': 'Personal Assets of Proprietors'},
        ),
        migrations.AlterModelOptions(
            name='propertiesproposed',
            options={'verbose_name': 'Proposed Property', 'verbose_name_plural': 'Proposed Properties'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RenameField(
            model_name='otherparticulars',
            old_name='monnths_during_the_current_year',
            new_name='months_during_the_current_year',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='acknowledgement_y1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acknowledgement Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='acknowledgement_y2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acknowledgement Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='acknowledgement_y3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acknowledgement Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='date_of_itr_filling_y1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date of ITR Filing Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='date_of_itr_filling_y2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date of ITR Filing Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='date_of_itr_filling_y3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date of ITR Filing Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='pan_y1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PAN Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='pan_y2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PAN Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='pan_y3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PAN Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_gross_income_y1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Gross Income Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_gross_income_y2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Gross Income Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_gross_income_y3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Gross Income Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_taxable_income_y1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Taxable Income Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_taxable_income_y2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Taxable Income Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='total_taxable_income_y3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Taxable Income Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ITR Filler Properly Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ITR Filler Properly Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ITR Filler Properly Year 3'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='year1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year 1'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='year2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year 2'),
        ),
        migrations.AlterField(
            model_name='itrverification',
            name='year3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year 3'),
        ),
        migrations.CreateModel(
            name='AdharImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_images', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'Aadhar Image',
                'verbose_name_plural': 'Aadhar Images',
            },
        ),
        migrations.CreateModel(
            name='AdharImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_images', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'Aadhar Image',
                'verbose_name_plural': 'Aadhar Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.applicant')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='PanImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'PAN Image',
                'verbose_name_plural': 'PAN Images',
            },
        ),
        migrations.CreateModel(
            name='PanImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'PAN Image',
                'verbose_name_plural': 'PAN Images',
            },
        ),
        migrations.DeleteModel(
            name='GstImages',
        ),
    ]
