# Generated by Django 5.0.3 on 2024-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0002_remove_coapplicant_bv_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
