# Generated by Django 5.0.3 on 2024-07-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0003_guarantor_rv_area_of_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/'),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='sev_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='sev_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_in_affiliations', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_establishment', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('award_won', models.BooleanField(blank=True, null=True)),
                ('any_change_in_reg_office', models.BooleanField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_verification', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheetAndPLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('net_income', models.IntegerField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_buyers', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsOfAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(blank=True, max_length=2, null=True)),
                ('name_of_buyers', models.CharField(blank=True, max_length=100, null=True)),
                ('nature_of_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_of_associates', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_assets', models.IntegerField(blank=True, null=True)),
                ('policy_number', models.IntegerField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, max_length=100, null=True)),
                ('sum_assured', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_covered', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_details', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ItrVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whether_itr_filler_properly', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_itr_filling', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledgement', models.IntegerField(blank=True, null=True)),
                ('total_gross_income', models.IntegerField(blank=True, null=True)),
                ('total_taxable_income', models.IntegerField(blank=True, null=True)),
                ('status_income', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_verification', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_plot_accessibility_proximity_to_other_units', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_raw_materials_and_sources', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_process', models.CharField(blank=True, max_length=100, null=True)),
                ('major_branded_and_imported_machines_installed', models.CharField(blank=True, max_length=100, null=True)),
                ('pollution_control', models.CharField(blank=True, max_length=100, null=True)),
                ('power_connected_load_and_backup_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory_wip_finished_goods_at_the_site', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_security_perishability_susceptibility_to_fire_and_weather', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('workers_split_of_temporary_and_permanent_any_unions', models.CharField(blank=True, max_length=100, null=True)),
                ('history_of_any_strikes_any_child_labour_working_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_entities', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='OtherParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monnths_during_the_current_year', models.CharField(blank=True, max_length=100, null=True)),
                ('purchases', models.CharField(blank=True, max_length=100, null=True)),
                ('sales', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_particulars', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAssetsOfProprietor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_personal_assets', models.CharField(blank=True, max_length=100, null=True)),
                ('description_of_assets_owned', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_in_rs', models.CharField(blank=True, max_length=100, null=True)),
                ('whether_any_security', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_assets', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesProposed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_property_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_property_1_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_property_2_or_3_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('address_property_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_property_2_or_3', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('whether_original_title_deeds', models.BooleanField(blank=True, null=True)),
                ('types_of_documents', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_proposed', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_suppliers', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='kapp.applicant')),
            ],
        ),
    ]
