# Generated by Django 5.0.3 on 2024-07-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0004_applicant_rv_constitution_of_buisness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itrverification',
            old_name='acknowledgement',
            new_name='acknowledgement_y1',
        ),
        migrations.RenameField(
            model_name='itrverification',
            old_name='total_gross_income',
            new_name='acknowledgement_y2',
        ),
        migrations.RenameField(
            model_name='itrverification',
            old_name='total_taxable_income',
            new_name='acknowledgement_y3',
        ),
        migrations.RenameField(
            model_name='itrverification',
            old_name='date_of_itr_filling',
            new_name='date_of_itr_filling_y1',
        ),
        migrations.RenameField(
            model_name='itrverification',
            old_name='status_income',
            new_name='date_of_itr_filling_y2',
        ),
        migrations.RenameField(
            model_name='itrverification',
            old_name='whether_itr_filler_properly',
            new_name='date_of_itr_filling_y3',
        ),
        migrations.RemoveField(
            model_name='detailsofassociate',
            name='sl_no',
        ),
        migrations.AddField(
            model_name='applicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coapplicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_gross_income_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_gross_income_y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_gross_income_y3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_taxable_income_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_taxable_income_y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='total_taxable_income_y3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itrverification',
            name='whether_itr_filler_properly_y3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedetails',
            name='sum_assured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('financial', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='kapp.applicant')),
            ],
        ),
    ]
