# Generated by Django 5.0.3 on 2024-07-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0006_conclusion_delete_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaryy', to='kapp.applicant'),
        ),
    ]
