# Generated by Django 5.0.3 on 2024-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0008_delete_conclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheetandplaccount',
            old_name='net_income',
            new_name='net_income1',
        ),
        migrations.RenameField(
            model_name='balancesheetandplaccount',
            old_name='year',
            new_name='year1',
        ),
        migrations.AddField(
            model_name='balancesheetandplaccount',
            name='net_income2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetandplaccount',
            name='net_income3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetandplaccount',
            name='year2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetandplaccount',
            name='year3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
