# Generated by Django 5.0.3 on 2024-07-08 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0010_detailsofassociate_slno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('identity', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_conclusion', to='kapp.applicant')),
            ],
        ),
    ]
