# Generated by Django 5.0.3 on 2024-07-08 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0012_itrverification_pan_y1_itrverification_pan_y2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantImageBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='applicant_images_business/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessimages', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='CoApplicantImageBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coapplicant_images_business/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessimages', to='kapp.coapplicant')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorImageBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guarantor_images_business/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessimages', to='kapp.guarantor')),
            ],
        ),
    ]
