# Generated by Django 5.0.3 on 2024-07-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0013_applicantimagebusiness_coapplicantimagebusiness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdharImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_images', models.ImageField(blank=True, null=True, upload_to='aadhar_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='GstImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PanImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.applicant')),
            ],
        ),
    ]
