# Generated by Django 5.0.3 on 2024-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0014_adharimages_gstimages_panimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adharimages',
            name='aadhar_images',
        ),
        migrations.AddField(
            model_name='adharimages',
            name='adhar_images',
            field=models.ImageField(blank=True, null=True, upload_to='adhar_images/'),
        ),
    ]
