# Generated by Django 5.0.3 on 2024-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation with Met Person'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation with Met Person'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='bv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_gstin_udyam_others_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSTIN/Udyam/Others No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_met_person_at_business_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Business Place'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_nature_of_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nature of Business'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_designation_of_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Designation'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ev_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_area_of_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of House'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_color_of_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color of House'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_constitution_of_buisness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Constitution of Business'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_duration_to_stay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration to Stay'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_e_bill_or_water_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='rv_e_bill_water_tax_documents/', verbose_name='E-Bill or Water Tax Document'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_met_person_at_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Met Person at Home'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_neighbour_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Neighbour Contact No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_neighbour_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighbour Name'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_num_of_persons_earning',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Earning'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_num_of_persons_living',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons Living'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_ownership_proof_type',
            field=models.CharField(blank=True, choices=[('E-Bill/Water Tax', 'E-Bill/Water Tax')], max_length=20, null=True, verbose_name='Ownership Proof Type'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN No'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_premises_is',
            field=models.BooleanField(blank=True, null=True, verbose_name='Premises Is'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation with Met Person'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_residency_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residency Status'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_details_confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details Confirmed By'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='sev_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation Met Person with Applicant'),
        ),
    ]
