# Generated by Django 5.0.3 on 2024-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0002_alter_applicant_bv_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstimages',
            name='gst_images',
            field=models.ImageField(blank=True, null=True, upload_to='gst_images/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='bv_relation_met_person_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Met Person with Applicant'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='rv_relation_with_met_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation of Applicant/Co-Applicant/Guarantor with met person'),
        ),
    ]
