# Generated by Django 5.0.3 on 2024-07-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0005_alter_adharimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstimages',
            name='Guarantor',
        ),
        migrations.RemoveField(
            model_name='gstimages',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='gstimages',
            name='coapplicant',
        ),
        migrations.RemoveField(
            model_name='panimages',
            name='Guarantor',
        ),
        migrations.RemoveField(
            model_name='panimages',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='panimages',
            name='coapplicant',
        ),
        migrations.CreateModel(
            name='AdharImagesOfApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_images', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.applicant')),
            ],
            options={
                'verbose_name': 'Aadhar Image',
                'verbose_name_plural': 'Aadhar Images',
            },
        ),
        migrations.CreateModel(
            name='AdharImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_images', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'Aadhar Image',
                'verbose_name_plural': 'Aadhar Images',
            },
        ),
        migrations.CreateModel(
            name='AdharImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_images', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'Aadhar Image',
                'verbose_name_plural': 'Aadhar Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.applicant')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='GstImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_images', models.ImageField(blank=True, null=True, upload_to='gst_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'GST Image',
                'verbose_name_plural': 'GST Images',
            },
        ),
        migrations.CreateModel(
            name='PanImagesOfApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.applicant')),
            ],
            options={
                'verbose_name': 'PAN Image',
                'verbose_name_plural': 'PAN Images',
            },
        ),
        migrations.CreateModel(
            name='PanImagesOfCoApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('coapplicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.coapplicant')),
            ],
            options={
                'verbose_name': 'PAN Image',
                'verbose_name_plural': 'PAN Images',
            },
        ),
        migrations.CreateModel(
            name='PanImagesOfGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_images', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_images', to='kapp.guarantor')),
            ],
            options={
                'verbose_name': 'PAN Image',
                'verbose_name_plural': 'PAN Images',
            },
        ),
        migrations.DeleteModel(
            name='AdharImages',
        ),
        migrations.DeleteModel(
            name='GstImages',
        ),
        migrations.DeleteModel(
            name='PanImages',
        ),
    ]
