# Generated by Django 5.0.3 on 2024-07-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0006_remove_gstimages_guarantor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherparticulars',
            old_name='monnths_during_the_current_year',
            new_name='months_during_the_current_year',
        ),
    ]
